spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

yappy.merchant-id=mock-merchant
yappy.secret-key=mock-secret

yappy.base-url=http://localhost:3000
yappy.endpoint-token=/auth/merchant/validate
yappy.endpoint-order=/payment/order/create

yappy.webhook-url=http://localhost:8080/api/yappy-webhook